"""add reporting fields to upload_records and screening_runs

Revision ID: 1c23407928e3
Revises: 89d0f8843140
Create Date: 2026-04-16 23:46:22.406219

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c23407928e3"
down_revision: str | Sequence[str] | None = "89d0f8843140"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("screening_runs", sa.Column("reviewer_name", sa.Text(), nullable=True))
    op.add_column("screening_runs", sa.Column("review_notes", sa.Text(), nullable=True))
    op.add_column("upload_records", sa.Column("source_label", sa.Text(), nullable=True))
    op.add_column("upload_records", sa.Column("search_strategy_used", sa.Text(), nullable=True))
    op.add_column("upload_records", sa.Column("limits_applied", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upload_records", "limits_applied")
    op.drop_column("upload_records", "search_strategy_used")
    op.drop_column("upload_records", "source_label")
    op.drop_column("screening_runs", "review_notes")
    op.drop_column("screening_runs", "reviewer_name")
    # ### end Alembic commands ###
