"""add_review_type_to_search_runs

Revision ID: 9b41c7258fc3
Revises: b3728baac143
Create Date: 2026-04-14 23:50:44.687924

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b41c7258fc3"
down_revision: str | Sequence[str] | None = "b3728baac143"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("search_runs", sa.Column("review_type", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("search_runs", "review_type")
    # ### end Alembic commands ###
